Repository codistica/codistica-js, pull requests merged in 2020-04, with the labels that each got.

#6 [bugfix] - Husky hooks exit code problem
  package.json
  yarn.lock
Labels: Fix, ⏳ Pending

#7 [feature] - Implement @codistica/babel-preset-default package
  .jsdocrc.js
  babel.config.js
  configs/babel/babel-plugin-banner.js
  configs/babel/babel-plugin-proposal-class-properties.js
  configs/babel/babel-plugin-transform-runtime.js
  configs/babel/babel-preset-env.js
  configs/babel/babel-preset-flow.js
  configs/babel/babel-preset-react.js
  configs/babel/babel-test-react-package.js
  package.json
  yarn.lock
Labels: New

#8 [feature] - Docs and templates update
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: Docs, ⏳ Pending

#9 [feature] - Implement @codistica/eslint-config-default package
  .eslintrc.js
  package.json
  yarn.lock
Labels: new

#10 [feature] - Implement @codistica/prettier-config-default package
  .prettierrc.js
  package.json
  yarn.lock
Labels: new

#14 [feature] - Add CHANGELOG.md files to each package
  CHANGELOG.md
  CONTRIBUTING.md
  packages/codistica-browser/CHANGELOG.md
  packages/codistica-core/CHANGELOG.md
  packages/codistica-dev-tools/CHANGELOG.md
  packages/codistica-node/CHANGELOG.md
  packages/codistica-react/CHANGELOG.md
  packages/codistica-scriptfiber/CHANGELOG.md
  packages/codistica-types/CHANGELOG.md
Labels: docs

#15 [feature] - Improve ESLint config
  .eslintrc.js
Labels: polish

#21 [bugfix] - Remove import extensions preventing flow detection.
  .eslintrc.js
  packages/codistica-react/CHANGELOG.md
  packages/codistica-react/package.json
  packages/codistica-react/src/index.js
Labels: fix

#22 [feature] - Adjust demo package to match project conventions.
  .eslintrc.js
  CHANGELOG.md
  package.json
  packages/codistica-demo/.flowconfig
  packages/codistica-demo/package.json
  packages/codistica-demo/src/app.js
  packages/codistica-demo/src/app.test.js
  packages/codistica-demo/src/index.js
  packages/codistica-demo/src/serviceWorker.js
  tsconfig.json
  yarn.lock
Labels: fix

#25 [feature] - Add coverage feedback on pull-requests.
  .github/workflows/pull-request.yml
  CHANGELOG.md
  package.json
Labels: new
